//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Belgeler
    {
        public int Id { get; set; }
        public int PersonelId { get; set; }
        public string BelgeAdi { get; set; }
        public string DosyaYolu { get; set; }
        public int BelgeTipi { get; set; }
    
        public virtual PersonelOzlukBilgileri PersonelOzlukBilgileri { get; set; }
    }
}
