//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzinTakip
    {
        public int Id { get; set; }
        public int PersonelId { get; set; }
        public System.DateTime IzinTalepTarihi { get; set; }
        public System.DateTime IzinBaslangicTarihi { get; set; }
        public System.DateTime İzinBitisTarihi { get; set; }
        public int IzinliGunSayisi { get; set; }
        public int IzinTipi { get; set; }
    
        public virtual PersonelOzlukBilgileri PersonelOzlukBilgileri { get; set; }
    }
}
