//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelOzlukBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonelOzlukBilgileri()
        {
            this.Belgeler = new HashSet<Belgeler>();
            this.IzinTakip = new HashSet<IzinTakip>();
            this.PersonelCocuk = new HashSet<PersonelCocuk>();
            this.PersonelEgitim = new HashSet<PersonelEgitim>();
            this.PersonelKiyafet = new HashSet<PersonelKiyafet>();
            this.PersonelPuantaj = new HashSet<PersonelPuantaj>();
            this.PersonelSaglikDurumlari = new HashSet<PersonelSaglikDurumlari>();
        }
    
        public int Id { get; set; }
        public string TcKimlik { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Unvan { get; set; }
        public string KurumSicilNo { get; set; }
        public string CepTelefonu { get; set; }
        public string Eposta { get; set; }
        public bool MedeniDurum { get; set; }
        public string EvAdresi { get; set; }
        public string Askerlik { get; set; }
        public string Ehliyet { get; set; }
        public bool EngellilikDurumu { get; set; }
        public int DepartmanId { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public System.DateTime İseGirisTarihi { get; set; }
        public bool AktifPasif { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public string EsiTc { get; set; }
        public string EsiAdiSoyadi { get; set; }
        public string EsiTelefon { get; set; }
        public Nullable<bool> EsiIsDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Belgeler> Belgeler { get; set; }
        public virtual Departmanlar Departmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzinTakip> IzinTakip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelCocuk> PersonelCocuk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelEgitim> PersonelEgitim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelKiyafet> PersonelKiyafet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelPuantaj> PersonelPuantaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelSaglikDurumlari> PersonelSaglikDurumlari { get; set; }
    }
}
