//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelSaglikDurumlari
    {
        public int Id { get; set; }
        public int PersonelId { get; set; }
        public bool Alerji { get; set; }
        public bool KalpHastaligi { get; set; }
        public bool KasEklem { get; set; }
        public bool GormeKusuru { get; set; }
        public bool IsitmeKaybi { get; set; }
        public bool BagisiklikGuclugu { get; set; }
        public bool KronikHastalik { get; set; }
        public bool AstimKoah { get; set; }
        public bool SindirimRahatsizliklari { get; set; }
        public string Aciklama { get; set; }
        public bool RuhsalHastalik { get; set; }
        public bool ZihinselHastalik { get; set; }
        public string KanGrubu { get; set; }
    
        public virtual PersonelOzlukBilgileri PersonelOzlukBilgileri { get; set; }
    }
}
